### ISSUE TITLE
Paragraph about GG

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/Soss-probprog#3]
We need a section about the broad capabilities and limitations of GG, from a user's perspective. It's important here for us to distinguish things that just haven't been implemented yet in GG from any inherent limitations in the fundamental design. I guess there's an ordering of responses to any "can GG do X" for some thing X:

1. Yes
2. Yes, with some minor (non-breaking) changes
3. Yes, with breaking changes. May be possible in GG 2.0
4. This may be possible, but would require rethinking GG from scratch
5. This cannot be done

We probably don't need this degree of detail in the paper, but hopefully this might be of some help in thinking about it

**Comment by thautwarm** [comment]
I failed at finishing [this document](https://github.com/thautwarm/GeneralizedGenerated.jl/blob/master/capabilities.md) for GG's capabilities, and I think I'd better directly answer the questions here, which can help your paper writing.

Firstly, the most explicit contribution of GG is allowing defining closures inside generated functions.

Then, if we regard generating full-featured Julia code as "full capabilities", the current restrictions are:
1. lack of support for comprehensions
   ```julia
   mk_function(:(() -> [i for i in 1:10]))
   ERROR: The function body AST defined by this @generated function is not pure. This likely means it contains a closure or comprehension.
   ```
2. lack of support for multiple dispatch
   ```julia
   runtime_eval(quote
   function f(x::Int)
      x + 1
   end
   function f(x::Float32)
      x * 2
   end
   f
   end)
   ```
   equals to
    ```julia
     f = (x::Int) -> x + 1
     f = (x::Float32) -> x * 2
     f
    ```
3. lack of support for data type definition
   ```julia
    runtime_eval(quote struct S end end)
   ```
4. lack of support for defining macros and applying macros
   ```julia
    mk_function(quote
       macro mk_func()
            :(x -> x + 1)
       end
       @mk_func
    end
   ``` 

Other than above things, all features supported by Julia should be supported to generate with GG stuffs. 

Using these labels
 > 1. Yes
 > 2. Yes, with some minor (non-breaking) changes
 > 3. Yes, with breaking changes. May be possible in GG 2.0
 > 4. This may be possible, but would require rethinking GG from scratch
 > 5. This cannot be done

to classify each existing restriction,

For the restriction `1. lack of support for comprehensions`, the label is `2. Yes, with some minor (non-breaking) changes`. Julia uses some special kind of ASTs(`Expr(:filter, ...)`, etc) to represent comprehensions, and implementing them just needs to map those ASTs to some builtin functions provided in `Base` or `Core`.

For the restriction `2. lack of support for multiple dispatch`, the label is `3. Yes, with breaking changes. May be possible in GG 2.0`. It requires a partial re-implementation of Julia's type system, and only making a `RuntimeFn` type for encoding Julia functions is not enough. A `RuntimeMethod` needs to be made, and `RuntimeFn` needs breaking changes to work with dispatching to `RuntimeMethod`.

For the restriction `3. lack of support for data type definition`, the label is `5. This cannot be done`. In fact it's still possible, but doing this IMO is quite evil. I strongly reject this.

For the restriction `4. lack of support for defining macros and applying macros`, the label is `2. Yes, with some minor (non-breaking) changes`. In the generated code, we can now apply existing macros, but defining macros and applying the macros defined there is not allowed now. However it's not a difficult thing to implement. By transforming the macro definitions into its function forms(just as what Julia compiler did), and finding out the callsites of these macros, we can simply support this feature. However, note that, before implementing multiple dispatch in GG, the macro definition in generated code still cannot use multiple dispatch(like `macro f(x::Symbol, y::Expr) ...`.

**Comment by thautwarm** [comment]
Also, about the explanation of using GG in Soss. Thanks to Chris, today I tidy up things at [here](https://raw.githubusercontent.com/thautwarm/GeneralizedGenerated.jl/master/capabilities.md), though this part is commented now due to I failed at giving good examples.

GG stuffs is a good tool for any kind of domain specific modeling. A `tagful`(opposite to the `tagless`) DSL, requires a lot of data types(**Models**) to represent the programs of the domain specific languages.
We can see this kind of things in

- [Yao.jl(Quantum Computing)](https://github.com/QuantumBFS/Yao.jl)
- [Luxor.jl(GUI)](https://github.com/JuliaGraphics/Luxor.jl)
- [Soss.jl(PPL)](https://github.com/cscherrer/Soss.jl)
- [ModelingToolKit.jl(General Modeling)](https://github.com/JuliaDiffEq/ModelingToolkit.jl)

There're 2 advantages of using GG.

## Run Compiled Code Instead of Interpretation

The first is, without GG, when executing the models of a DSL, it's proceeding **in an interpretation way**, and GG can make things go **in a compilation way**.

I present a mimimal example of interpreting DSLs can be found at [a terminal plot language](https://github.com/thautwarm/static-resources/blob/master/GG/modeling-examples/terminal-plot-tagful-approach.jl#L61).

Thanks to Julia's JIT feature, when the **Model** types(like subtypes  of `Statement` in Soss) are not very high level, i.e., can provide values for engaging interpretation without extra computations, the interpretation mode can still be fast, although the optimizations cannot be as easy as that of a compilation mode.

## Specialization using Runtime Information

The we come to the second advantage of using GG, it's about optimizations.

GG can do specialization in runtime and generate more efficient code. ModelingToolKit.jl is depending on this, from the explanation given by Chris, in the algorithms he is working with, based on the runtime information, there can be some boolean identities which could be just constants, thus the algorithms can be specialized using GG. ModelingToolKit.jl provides scenarios that generating functions can be necessary, and runtime specializations can be pretty beneficial.

**Comment by thautwarm** [comment]
For Soss itself, firstly, we make sure executing Soss models are always referring to the compiled code, but the benefits about compilation might still need some examinations. In fact, when I'm doing benchmark on my small DSL [here](https://github.com/thautwarm/static-resources/blob/master/GG/modeling-examples/terminal-plot-bench.jl), there're only 2%~4% speed-up of solely compilation.

The most important part could be specialization using runtime information. 

Besides the providing the capabilities of doing specialization, by using GG's generated functions, it is also much more easy to implement, because we don't have to care about how to write a fast code generator.

When doing specialization in interpretation, the code for specializations is also needed to be implemented efficient. We have to avoid object allocation, avoid runtime type checking(`isa`), which is all unnecessary when writing specializations in a code generator.

For my minimal examplar DSL, I implemented specialization for the code generator, [it's easy](https://github.com/thautwarm/static-resources/blob/master/GG/modeling-examples/terminal-plot-compiler.jl#L100). However, when I'm trying to do this [here](https://github.com/thautwarm/static-resources/blob/master/GG/modeling-examples/terminal-plot-high-order.jl#L74), I feel painful: I think I shouldn't use helper functions or create additional flag objects to exchange convenience with execution time.

**Comment by thautwarm** [comment]
These seem to be all, @cscherrer .

**Comment by thautwarm** [comment]
Also, the specialization used in Soss should contain
- [symbolic/codegen](https://github.com/cscherrer/Soss.jl/blob/master/src/symbolic/codegen.jl#L61)
- [loading arguments from namedtuples](https://github.com/cscherrer/Soss.jl/blob/master/src/core/utils.jl#L182), as you know, we use Parameters.jl before, which is very slow. Current design keeps both convenience and efficiency.

**Comment by thautwarm** [comment]
Also, Soss already generates julia expressions from model types. Those expressions contain functions, so GG also helps the evaluating runtime functions from ASTs.
